volumes:
  db_data:

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DATABASE_URL: mongodb+srv://doadmin:XEd4U039567rTs8@db-mongodb-fra1-89105-e87583ac.mongo.ondigitalocean.com/admin
  DEEPL_API_KEY: ${DEEPL_API_KEY}
  OPENAI_API_KEY: ${OPENAI_API_KEY}

services:
  db:
    image: mongo:latest
    volumes:
      - db_data:/data/db
    restart: unless-stopped
    ports:
      - '27017:27017'
    healthcheck:
      test: echo 'db.stats()' | mongo --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  app:
    image: bergnerbackend:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8080:8080'
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]

  migrate:
    image: bergnerbackend:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      db:
        condition: service_healthy
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0

  revert:
    image: bergnerbackend:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      db:
        condition: service_healthy
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0

  queues:
    image: bergnerbackend:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      db:
        condition: service_healthy
    command: ["queues", "--scheduled"]
    deploy:
      replicas: 1
